ashare:
  turnover_risk: 1.0
  northbound_risk: 1.2
  margin_risk: 0.8
  main_fund_risk: 1.0
  etf_flow_risk: 0.8

global:
  us_equity_risk: 1.0
  volatility_risk: 1.0
  cny_fx_risk: 0.8
  jpy_risk: 0.8
  gold_risk: 0.8
  cibr_risk: 0.8
