T1:
  market_sentiment: 0.30
  turnover: 0.20
  north_nps: 0.15
  emotion: 0.15
  margin: 0.10
  global_lead: 0.10

T5:
  market_sentiment: 0.15
  turnover: 0.20
  north_nps: 0.15
  emotion: 0.10
  margin: 0.20
  global_lead: 0.20
